[package]
name = "strip-greek-accents"
version = "0.1.0"
authors = ["jsMRSoL <si_pitt@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
regex = "1.3"